name: Bot Final 2024

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install -r requirements.txt
    - name: Debug y ejecutar
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        pwd
        ls -la
        find . -name "main.py"
        timeout 21600 python main.py || true
