name: Discord Bot 24/7

on:
  schedule:
    - cron: '0 */6 * * *'  # Cada 6 horas
  workflow_dispatch:  # Ejecutar manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Discord Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        timeout 21000 python ./main.py || true
        
    - name: Post Setup Python
      run: echo "Bot execution completed"
      
    - name: Post Checkout code
      run: echo "Workflow finished"
      
    - name: Complete job
      run: echo "Job completed successfully"
