name: Discord Bot 2024

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  bot-runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Dependencies
      run: pip install -r requirements.txt
      
    - name: Run Bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        echo "Iniciando bot..."
        timeout 21600 python main.py || echo "Bot terminado"
