name: Bot Discord 24/7

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install -r requirements.txt
    - env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        echo "=== DEBUGGING COMPLETO ==="
        echo "Directorio actual:"
        pwd
        echo "=== LISTADO COMPLETO ==="
        ls -la
        echo "=== BUSCANDO main.py ==="
        find . -name "main.py" -type f
        echo "=== VERIFICANDO PERMISOS ==="
        ls -la main.py
        echo "=== VERIFICANDO TOKEN ==="
        echo "TOKEN definido: $([[ -n $TOKEN ]] && echo 'SÍ' || echo 'NO')"
        echo "=== CONTENIDO DIRECTORIO ==="
        tree . || ls -R
        echo "=== EJECUTANDO BOT ==="
        timeout 21600 python main.py || true
        echo "=== FIN EJECUCIÓN ==="
